### ISSUE TITLE
支持

### ISSUE THREAD

**Issue by ZHAISHENKING** [Hopetree/izone-docker#1]
老哥要出docker版的博客吗？期待更新

**Comment by Hopetree** [comment]
@ZHAISHENKING demo已经写好了，容器化已经实现了，现在我在整合虚拟化和容器化的版本，让博客可以同时支持两种部署方式，近期会在博客上面更新文章说明容器化的版本，感兴趣可以关注一下，容器化可以把部署的时间从4-5个小时缩短到半个小时以内，最重要的是可以有效的避开很多坑
