### ISSUE TITLE
Doc for third-party login

### ISSUE THREAD

**Issue by hermanzhaozzzz** [Hopetree/izone-docker#15]
博主的izone和docker版很好用，但是第三方登录的时候，我没搞清楚如何进行token设置，也没有在wiki或者代码中找到说明。

![](http://_pic.zhaohuanan.cc:7777/images/2023/11/14/20231114162938.png)
请问有计划补充一个文档说明吗，如果没有的话，想请教一下具体如何设置微博和GitHub的token，以及管理后台如何填写

感谢！

**Comment by Hopetree** [comment]
这个你可以去看看django-allauth的官方文档，然后再去搜一些相关的文章看看，我博客搞的太久了有点忘记了要做哪些操作

**Comment by hermanzhaozzzz** [comment]
好，谢谢博主！
